In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
test_df=pd.read_csv('test.csv')
train_df=pd.read_csv('train.csv')

In [ ]:
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
# ONE-HOT ENCODING
train_df=pd.get_dummies(train_df,columns=['Sex'])
test_df=pd.get_dummies(test_df,columns=['Sex'])
train_df=pd.get_dummies(train_df,columns=['Embarked'])
test_df=pd.get_dummies(test_df,columns=['Embarked'])
# FILL MISSING AGE WITH MEDIAN
train_df['Age']=train_df['Age'].fillna(train_df['Age'].median())
test_df['Age']=test_df['Age'].fillna(test_df['Age'].median())
# FILL FARE WITH MEDIAN IN TEST DATA
test_df['Fare']=test_df['Fare'].fillna(test_df['Fare'].median())
# MIN-MAX-SCALER OF FARE in train_df
scaler=MinMaxScaler()
train_df['Fare']=scaler.fit_transform(train_df[['Fare']])
train_df['Pclass']=scaler.fit_transform(train_df[['Pclass']])
train_df['Age']=scaler.fit_transform(train_df[['Age']])
train_df['SibSp']=scaler.fit_transform(train_df[['Fare']])
train_df['Parch']=scaler.fit_transform(train_df[['Parch']])
# MIN-MAX-SCALER OF FARE in test_df
test_df['Fare']=scaler.fit_transform(test_df[['Fare']])
test_df['Pclass']=scaler.fit_transform(test_df[['Pclass']])
test_df['Age']=scaler.fit_transform(test_df[['Age']])
test_df['SibSp']=scaler.fit_transform(test_df[['Fare']])
test_df['Parch']=scaler.fit_transform(test_df[['Parch']])

In [ ]:
test_df

,PassengerId,Pclass,Name,Age,SibSp,Parch,Fare,Cabin,Sex_female,Sex_male,...,Ticket_SOTON/OQ 392083,Ticket_STON/O 2. 3101268,Ticket_STON/O 2. 3101291,Ticket_STON/O2. 3101270,Ticket_STON/OQ. 369943,Ticket_W./C. 14260,Ticket_W./C. 14266,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W.E.P. 5734
0,892,1.0,"Kelly, Mr. James",0.452723,0.015282,0.000000,0.015282,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
1,893,1.0,"Wilkes, Mrs. James (Ellen Needs)",0.617566,0.013663,0.000000,0.013663,NaN,True,False,...,False,False,False,False,False,False,False,False,False,False
2,894,0.5,"Myles, Mr. Thomas Francis",0.815377,0.018909,0.000000,0.018909,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
3,895,1.0,"Wirz, Mr. Albert",0.353818,0.016908,0.000000,0.016908,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
4,896,1.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0.287881,0.023984,0.111111,0.023984,NaN,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,1.0,"Spector, Mr. Woolf",0.353818,0.015713,0.000000,0.015713,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
414,1306,0.0,"Oliva y Ocana, Dona. Fermina",0.512066,0.212559,0.000000,0.212559,C105,True,False,...,False,False,False,False,False,False,False,False,False,False
415,1307,1.0,"Saether, Mr. Simon Sivertsen",0.505473,0.014151,0.000000,0.014151,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
416,1308,1.0,"Ware, Mr. Frederick",0.353818,0.015713,0.000000,0.015713,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
417,1309,1.0,"Peter, Master. Michael J",0.353818,0.043640,0.111111,0.043640,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
#X=train_df[['Pclass','Sex_female','Sex_male','Age','SibSp','Parch','Fare','Embarked_Q']]
#Y=train_df['Survived']
#test_X= test_df[['Pclass','Sex_female','Sex_male','Age','SibSp','Parch','Fare','Embarked_S']]
X = train_df.drop(columns=[
    'PassengerId',
    'Survived',
    'Name',
    'Ticket',
    'Cabin'
])

Y = train_df['Survived']

test_X = test_df.drop(columns=[
    'PassengerId',
    'Name',
    'Ticket',
    'Cabin'
])

In [ ]:
# CHECK
train_df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,1.0,"Braund, Mr. Owen Harris",0.271174,0.014151,0.000000,A/5 21171,0.014151,NaN,False,True,False,False,True
1,2,1,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0.472229,0.139136,0.000000,PC 17599,0.139136,C85,True,False,True,False,False
2,3,1,1.0,"Heikkinen, Miss. Laina",0.321438,0.015469,0.000000,STON/O2. 3101282,0.015469,NaN,True,False,False,False,True
3,4,1,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0.434531,0.103644,0.000000,113803,0.103644,C123,True,False,False,False,True
4,5,0,1.0,"Allen, Mr. William Henry",0.434531,0.015713,0.000000,373450,0.015713,NaN,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,0.5,"Montvila, Rev. Juozas",0.334004,0.025374,0.000000,211536,0.025374,NaN,False,True,False,False,True
887,888,1,0.0,"Graham, Miss. Margaret Edith",0.233476,0.058556,0.000000,112053,0.058556,B42,True,False,False,False,True
888,889,0,1.0,"Johnston, Miss. Catherine Helen ""Carrie""",0.346569,0.045771,0.333333,W./C. 6607,0.045771,NaN,True,False,False,False,True
889,890,1,0.0,"Behr, Mr. Karl Howell",0.321438,0.058556,0.000000,111369,0.058556,C148,False,True,True,False,False
890,891,0,1.0,"Dooley, Mr. Patrick",0.396833,0.015127,0.000000,370376,0.015127,NaN,False,True,False,True,False

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X,Y)

LogisticRegression()

In [ ]:
test_df['Survived']=model.predict(test_X)

In [ ]:
test_df

,PassengerId,Pclass,Name,Age,SibSp,Parch,Fare,Cabin,Sex_female,Sex_male,...,Ticket_SOTON/OQ 392083,Ticket_STON/O 2. 3101268,Ticket_STON/O 2. 3101291,Ticket_STON/O2. 3101270,Ticket_STON/OQ. 369943,Ticket_W./C. 14260,Ticket_W./C. 14266,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W.E.P. 5734
0,892,1.0,"Kelly, Mr. James",0.452723,0.015282,0.000000,0.015282,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
1,893,1.0,"Wilkes, Mrs. James (Ellen Needs)",0.617566,0.013663,0.000000,0.013663,NaN,True,False,...,False,False,False,False,False,False,False,False,False,False
2,894,0.5,"Myles, Mr. Thomas Francis",0.815377,0.018909,0.000000,0.018909,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
3,895,1.0,"Wirz, Mr. Albert",0.353818,0.016908,0.000000,0.016908,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
4,896,1.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0.287881,0.023984,0.111111,0.023984,NaN,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,1.0,"Spector, Mr. Woolf",0.353818,0.015713,0.000000,0.015713,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
414,1306,0.0,"Oliva y Ocana, Dona. Fermina",0.512066,0.212559,0.000000,0.212559,C105,True,False,...,False,False,False,False,False,False,False,False,False,False
415,1307,1.0,"Saether, Mr. Simon Sivertsen",0.505473,0.014151,0.000000,0.014151,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
416,1308,1.0,"Ware, Mr. Frederick",0.353818,0.015713,0.000000,0.015713,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False
417,1309,1.0,"Peter, Master. Michael J",0.353818,0.043640,0.111111,0.043640,NaN,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
test_df[['PassengerId','Survived']].to_csv('submission.csv',index=False)

in data preprocessing we have seen
1.dropna
2.fillna(mean/median)
3.remove outlier(data_colums.Qunatile(0.25/0.75))
4.labelincoding,onehotincoding
5.